import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import { Text, Table, Button } from '@nextui-org/react';
import { ethers } from 'ethers';

const ExchangeScreen = () => {
  const [provider, setProvider] = useState<any>(undefined);
  const [signer, setSigner] = useState<any>(undefined);
  const [signerAddress, setSignerAddress] = useState<any>(undefined);

  useEffect(() => {
    const onLoad = async () => {
      //@ts-ignore
      const provider = await new ethers.providers.Web3Provider(window.ethereum);
      setProvider(provider);
    };

    onLoad();
  }, []);

  const getSigner = async (provider: any) => {
    provider.send('eth_requestAccounts', []);
    const signer = provider.getSigner();
    setSigner(signer);
  };

  const isConnected = () => signer !== undefined;

  const getWalletAddress = () => {
    signer.getAddress().then((address: any) => {
      setSignerAddress(address);
    });
  };

  if (signer !== undefined) {
    getWalletAddress();
  }

  return (
    <div className="min-h-screen py-8 px-60">
      <Head>
        <title>Exchange | Finesse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {isConnected() ? (
          <>
            <Text h6>{signerAddress}</Text>
          </>
        ) : (
          <Button className="mx-auto" onClick={() => getSigner(provider)}>
            Connect Wallet
          </Button>
        )}
        <Text h1 className="text-center">
          Finesse
        </Text>
        <Table>
          <Table.Header>
            <Table.Column>SONG</Table.Column>
            <Table.Column>ARTIST</Table.Column>
            <Table.Column>PRICE (MATIC)</Table.Column>
          </Table.Header>
          <Table.Body>
            <Table.Row key="1">
              <Table.Cell>Lose Yourself</Table.Cell>
              <Table.Cell>Eminem</Table.Cell>
              <Table.Cell>0.0075</Table.Cell>
            </Table.Row>
            <Table.Row key="2">
              <Table.Cell>Rap God</Table.Cell>
              <Table.Cell>Eminem</Table.Cell>
              <Table.Cell>0.0075</Table.Cell>
            </Table.Row>
          </Table.Body>
        </Table>
      </div>
    </div>
  );
};

export default ExchangeScreen;
