import Head from 'next/head';
import React from 'react';
import Navbar from '../components/Navbar';

const HomeScreen = () => {
  return (
    <div>
      <Head>
        <title>Finesse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className="text-white text-center">Finesse</div>
    </div>
  );
};

export default HomeScreen;
